### PR TITLE
Updated new code for the path issue on windows

### PR DESCRIPTION
**Pull request by DevHyperCoder**

### CODE REVIEW

**Comment by DevHyperCoder** [comment]
Use `const` variables instead of `let`.
Try not to make changes to the `gitCloneCommand` in `constants.ts`

**Comment by ofceab** [comment]
> 
> 
> Use `const` variables instead of `let`.
> Try not to make changes to the `gitCloneCommand` in `constants.ts`

okay noted

**Comment by ofceab** [comment]
> 
> 
> _No description provided._
okay noted

**Comment by DevHyperCoder** [comment]
@ofceab please TEST this on your machine ; Try to remove the separate `gitCloneCommand` and if it **WORKS**, merge it to master, Otherwise fix it please. If you don't get time, let us know and we won't bother you

**Pull request merged**
